### ISSUE TITLE
fail to import, notepad++

### ISSUE THREAD

**Issue by Mellivora123** [vkosuri/npp-robot#2]
fail to import

**Comment by vkosuri** [comment]
which version npp are you using? how you are importing?

**Comment by vkosuri** [comment]
Here are the steps if fallowed import lang-robot it went fine Here is screen shot of import 

> Lnaguage -> User Defined -> Import

![issue-2](https://cloud.githubusercontent.com/assets/13664257/12258079/cbd782a8-b931-11e5-8f04-f376576671ba.png)

Let me know if you need any further help on this issue?

**Comment by Dashengguilai** [comment]
My notepad++ version is 6.8.8...
I think I did the right steps to import your lang-robot.xml.
![capture](https://cloud.githubusercontent.com/assets/13506936/12286611/9951f29e-ba00-11e5-95a1-ab69f70ed686.PNG)

**Comment by vkosuri** [comment]
Thank you, could you please try url specified instructions below link and let me know

http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files#How_to_install_user_defined_language_files

**Comment by Dashengguilai** [comment]
* I just got the wrong lang-robot.xml...I right clicked the lang-robot.xml link and select 'save as' then it gave me the web page https://github.com/vkosuri/npp-robot/blob/master/lang-robot.xml. I didn't notice that i got the web page file instead of the correct xml configuration file.  
* Your syntax highlighter works quite well except with dark themes.  
* Thanks, great work! I can write robot framework scripts more efficiently now.

**Comment by vkosuri** [comment]
@Dashengguilai Thank you

**Comment by vkosuri** [comment]
@Dashengguilai if possible could you share dark theme screen shot?

**Comment by Dashengguilai** [comment]
![default](https://cloud.githubusercontent.com/assets/13506936/12386552/546c5336-be01-11e5-8c13-48a803bc7b4b.PNG)

**Comment by vkosuri** [comment]
@Mellivora123 thank you very much, if you are interested to submit PR for dark theme most welcome.

**Comment by Mellivora123** [comment]
Any suggestion for starters?

**Comment by vkosuri** [comment]
Please go through this link for udl http://udl20.weebly.com/ , all robotframework 3.0 keywords are placed in https://github.com/vkosuri/npp-robot/blob/master/robot_keywords.txt

**Comment by vkosuri** [comment]
no response from @Mellivora123, hence closing this issue
