### ISSUE TITLE
Fail to import lang-robot.xml

### ISSUE THREAD

**Issue by jamesxu2018** [vkosuri/npp-robot#3]
I fail to import the xml, it promt 'import fail', any comments?

notepad++ 7.3.2 32bit

D:\Program Files (x86)\Notepad++\plugins\lang-robot.xml

![image](https://cloud.githubusercontent.com/assets/27674327/26539645/320e72f4-4480-11e7-83fe-669689bd2f33.png)

![image](https://cloud.githubusercontent.com/assets/27674327/26539671/544254c6-4480-11e7-862a-d31ce8bd16c5.png)

**Comment by vkosuri** [comment]
Thanks looking into this issue, It works with Notepad 6.x version, it started failing with Notepad7.x versions.

**Comment by vkosuri** [comment]
It's observed after restarting my notepad++ application and try import [lang-robot.xml](https://github.com/vkosuri/npp-robot/blob/master/lang-robot.xml) it works fine. Could you please try the same and let me know?

**Comment by jamesxu2018** [comment]
I tried again, unluckily, I got the same failure.

**Comment by vkosuri** [comment]
Did you imported [lang-robot.xml](https://github.com/vkosuri/npp-robot/blob/master/lang-robot.xml)?

And also I tried on 7.3.3 version which build Mar 8 2017 which works fine. 

Could try to upgrade your notepad++ to 7.3.3 and try to use this [lang-robot.xml](https://github.com/vkosuri/npp-robot/blob/master/lang-robot.xml) and let me know your inputs?

![image](https://cloud.githubusercontent.com/assets/13664257/26569603/3c889e5e-4529-11e7-9674-071e83ac5d69.png)

**Comment by jamesxu2018** [comment]
Have another try at a different windows 10 notebook running notepad++ 7.3.3, but still fail to import, any further comment?

![image](https://cloud.githubusercontent.com/assets/27674327/26613012/1dce11ca-45eb-11e7-8c6b-a1eb16e1834a.png)

![image](https://cloud.githubusercontent.com/assets/27674327/26613021/2939c1c6-45eb-11e7-833b-5cb6bb86c223.png)

**Comment by vkosuri** [comment]
I think it is very similar to this issue https://github.com/vkosuri/npp-robot/issues/2#issuecomment-171339928

Are you doing like this as suggested @Mellivora123

- I just got the wrong lang-robot.xml...I right clicked the lang-robot.xml link and select 'save as' then it gave me the web page https://github.com/vkosuri/npp-robot/blob/master/lang-robot.xml. I didn't notice that i got the web page file instead of the correct xml configuration file.  
- Your syntax highlighter works quite well except with dark themes.  
- Thanks, great work! I can write robot framework scripts more efficiently now.

**Comment by vkosuri** [comment]
And also I just tried on Windows Machine 10 it works fine.

**Comment by jamesxu2018** [comment]
Thanks so much, as you mentioned, I got the wrong .xml as comment2, after correct it, I now can import the .xml successfully.

**Comment by peggymccoy** [comment]
I was able to successfully import the file, but instead of Blue - Keywords., Orange - Variables, Green - Comments.
I got Orange - comments, Blue - Random items, Green - nowhere, most text, including Keywords is unchanged.
